## Initialization and following ops must be in the same session- in the same block of a tf session

### with tf.Session as

In [1]:
import tensorflow as tf

# create a constant tensor : a matrix of (3,3)
# the values are random between 0 and 1
aTensor=tf.random_uniform((3,3),0,1)

# declare a variable inisalized with atensor

aTfVar=tf.Variable(initial_value=aTensor)

In [2]:
# Get an initializer operation to initialize the variable

anInitializer = tf.global_variables_initializer()

In [3]:
# Initialize the variable and prepare the print of the contents of

with tf.Session() as sess:
    sess.run(anInitializer)
    results=sess.run(aTfVar)
    print(results)

[[0.4417106  0.73774505 0.5244385 ]
 [0.60493183 0.3803625  0.49365628]
 [0.42586565 0.36597776 0.7435607 ]]


In [4]:
# combine 2 statements into one

with tf.Session() as sess:
    sess.run(anInitializer)
    print(sess.run(aTfVar))

[[0.5563413  0.6062114  0.24732554]
 [0.50989187 0.03952432 0.9868685 ]
 [0.6896409  0.3028692  0.92136824]]


In [5]:
# NOTES : Error if without initalizer
import tensorflow as tf
aTensor = tf.random_uniform((3,3),0,1)
aTfVar_2= tf.Variable(initial_value=aTensor)
anInitializer=tf.global_variables_initializer()

""" CAUSE ERROR
with tf.Session()as sess:
    results=sess.run(aTfVar_2)
"""    

' CAUSE ERROR\nwith tf.Session()as sess:\n    results=sess.run(aTfVar_2)\n'

In [6]:
# Notes : Error if not in the same session block of code

import tensorflow as tf
aTensor = tf.random_uniform((3,3),0,1)
aTfVar_2= tf.Variable(initial_value=aTensor)
anInitializer=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(anInitializer)
""" CAUSE ERROR
results=sess.run(aTfVar_2)
"""

' CAUSE ERROR\nresults=sess.run(aTfVar_2)\n'

In [7]:
# Notes: Do Nothing of without "results=..."and "print(...)"
import tensorflow as tf
aTensor = tf.random_uniform((3,3),0,1)
aTfVar_2= tf.Variable(initial_value=aTensor)
anInitializer=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(anInitializer)
    sess.run(aTfVar_2)

### using Interactive sessions

Notes: All the statement between the start and the close of tf.InteractveSession()are included in the same session

In [8]:
import tensorflow as tf
# start a tf.Interactivesession
sess=tf.InteractiveSession()

In [10]:
aTensor =tf.random_uniform((3,3),0,1)

In [11]:
aTfVar_3=tf.Variable(initial_value=aTensor)

In [17]:
# get an initializer operation to initialize the variable

anInitializer= tf.global_variables_initializer()


# Run the oepration initializer to actually initialize the variable

sess.run(anInitializer)




In [18]:
# Display the values of the initialized variable

sess.run(aTfVar_3)

array([[0.23431993, 0.90784085, 0.990983  ],
       [0.51216435, 0.3095702 , 0.4171977 ],
       [0.260857  , 0.54986095, 0.9466723 ]], dtype=float32)

In [19]:
# Must close the session
sess.close()

Notes: Display the values without =results=..." and "print(...)""

In [22]:
sess =tf.InteractiveSession()

aTfVar_4=tf.Variable(initial_value=aTensor)
anInitializer= tf.global_variables_initializer()
sess.run(anInitializer)


/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [23]:
# Display the values of the initialized variable

# without "results=..." and "print(...)"

sess.run(aTfVar_4)

array([[0.6114917 , 0.8027923 , 0.08910978],
       [0.47394943, 0.7392192 , 0.19350493],
       [0.18662214, 0.95374477, 0.2126013 ]], dtype=float32)

In [24]:
sess.close()

In [25]:
### Another example

import tensorflow as tf
sess=tf.InteractiveSession()
a=tf.constant(5.0)
b=tf.constant(6.0)
c=a*b

In [27]:
# we can use 'c.eval() without passing 'sess
print(c.eval())

30.0


In [29]:
sess.close()