In [1]:
## Using with tf.Session() as..

import tensorflow as tf
# declare a constant

a=tf.constant(10)
a

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [2]:
print(a)

Tensor("Const:0", shape=(), dtype=int32)


In [3]:
# to display the value of a constant
# MUST RUN A SESSION

with tf.Session() as sess:
    results=sess.run(a)
    print(results)

10


### Notes: Combine 2 statements

In [4]:
with tf.Session () as sess:
    print(sess.run(a))

10


In [6]:
## Notes: Do Nothing without "results="OR "print..(..)"

with tf.Session()as sess:
    sess.run(a)

In [8]:
### Using tf.InteractiveSession()

import tensorflow as tf

sess=tf.InteractiveSession()
b=tf.constant(20)
sess.run(b)


/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


20

In [9]:
sess.close()

### display Values :tf.Variables

In [11]:
import tensorflow as tf

aTensor =tf.random_uniform((3,3),0,1)

aTfVar_1=tf.Variable(initial_value=aTensor)

anInitializer= tf.global_variables_initializer()



In [12]:
with tf.Session()as sess:
    sess.run(anInitializer)
    results=sess.run(aTfVar_1)
    print(results)

[[0.49055254 0.5946895  0.38198984]
 [0.8191564  0.0561322  0.40597987]
 [0.6319128  0.4527613  0.29936934]]


### using tf.InteractiveSession()

In [13]:
import tensorflow as tf
# start a tf.Interactivesession
sess=tf.InteractiveSession()

aTensor =tf.random_uniform((3,3),0,1)

aTfVar_2=tf.Variable(initial_value=aTensor)
anInitializer2= tf.global_variables_initializer()



In [16]:
sess.run(anInitializer2)
sess.run(aTfVar_2)

array([[0.84402764, 0.87367463, 0.27105868],
       [0.06550479, 0.34995806, 0.79987717],
       [0.42106807, 0.18103302, 0.04922998]], dtype=float32)

In [17]:
sess.close()

### display values : tf.placeholder

In [20]:
import tensorflow as tf
x=tf.placeholder(tf.float32)

### example 1 :using with tf.Session() as ...

In [22]:
# Do Nothing

with tf.Session() as session:
    session.run([x],feed_dict={x:[10]})

In [24]:
with tf.Session() as session:
    result=session.run([x],feed_dict={x:[10]})
    print(result)

[array([10.], dtype=float32)]


### example 1 :using with tf.InteractiveSession() as ...

In [26]:
sess=tf.InteractiveSession()

sess.run([x],feed_dict={x:[20]})

[array([20.], dtype=float32)]

In [27]:
sess.close()

### example 2 :using with tf.Session() as ...

In [28]:
x=tf.placeholder(tf.float32, None)
y=x*2



In [30]:
with tf.Session() as sess:
    result=sess.run([y],feed_dict={x:[1,2,3]})
    print(result)

[array([2., 4., 6.], dtype=float32)]


### example 2 :using with tf.InteractiveSession() as ...


In [31]:
sess=tf.InteractiveSession()

sess.run([x],feed_dict={x:[1,3,5]})

[array([1., 3., 5.], dtype=float32)]

In [32]:
sess.close()